ALL_SYM = ['SPY', 'IVV', 'VOO', 'VTI', 'QQQ', 'VEA', 'IEFA', 'VTV', 'BND', 'AGG', 'VUG', 'VWO', 'IEMG', 'IWF', 'VIG', 
'IJH', 'IJR', 'GLD', 'VGT', 'VXUS', 'VO', 'IWM', 'BNDX', 'EFA', 'IWD', 'VYM', 'SCHD', 'XLK', 'ITOT', 'VB', 'VCIT', 
'XLV', 'TLT', 'BSV', 'VCSH', 'LQD', 'XLE', 'VEU', 'RSP', 'TQQQ', 'SQQQ', 'SPXS', 'SPXL', 'SOXL', 'SOXS', 'MMM', 'AOS', 
'ABT', 'ABBV', 'ACN', 'ATVI', 'ADM', 'ADBE', 'ADP', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALGN', 
'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AMD', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 
'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 
'ADSK', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BAC', 'BBWI', 'BAX', 'BDX', 'WRB', 'BRK.B', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 
'BK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'BG', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 
'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 'CNP', 'CDAY', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 
'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 
'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 
'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISH', 'DIS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DD', 'DXC', 'EMN', 
'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 
'ETSY', 'RE', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 
'FITB', 'FSLR', 'FE', 'FIS', 'FLT', 'FMC', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GNRC', 
'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 
'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 
'ILMN', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 
'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 
'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MRO', 'MPC', 
'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 
'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 
'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 
'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OGN', 'OTIS', 'PCAR', 'PKG', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 
'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 
'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'ROL', 
'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SNA', 
'SEDG', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 
'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 
'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VRSN', 
'VRSK', 'VZ', 'VRTX', 'VFC', 'VTRS', 'VICI', 'V', 'VMC', 'WAB', 'WBA', 'WMT', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 
'WST', 'WDC', 'WRK', 'WY', 'WHR', 'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS', 
'CVNA', 'DKNG', 'VXX', 'W', 'CHWY', 'PTON', 'TEAM', 'MDB', 'HOOD', 'MARA', 'AI', 'LYFT', 'BYND', 'RIOT', 'U', 'DOCU', 'TTD',
'UBER', 'JD', 'DDOG', 'CRWD', 'SQ', 'RBLX', 'SNAP', 'FUTU', 'TSM', 'LCID', 'UPST', 'TDOC', 'SNOW', 'BIDU', 'NIO', 'SHOP', 'ROKU', 
'OKTA', 'RIVN', 'ZM', 'WBD', 'SE', 'SOFI', 'META', 'TWLO', 'ZS', 'BABA', 'PLTR', 'PINS', 'PANW', 'ABNB', 'NET', 'COIN', 'BILI', 'ARM']

WEEKLY_EXP = ['MMM', 'ABT', 'ABBV', 'ACN', 'ATVI', 'ADM', 'ADBE', 'ADP', 
'AAP', 'AFL', 'ALB', 'ALGN', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMD', 'AAL', 'AXP', 'AIG', 'ABC', 'AMGN', 'ADI', 'APA', 'AAPL', 'AMAT', 'ANET', 'T', 'ADSK', 'BAC', 'BBWI', 'BAX', 'BBY', 'BIIB', 
'BLK', 'BA', 'BKNG', 'BMY', 'AVGO', 'CZR', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CAT', 'CBOE', 'CNC', 'CF', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CI', 'CSCO', 'C', 'CLX', 'CME', 'KO', 'CMCSA', 'CMA', 'CAG', 
'COP', 'STZ', 'GLW', 'COST', 'CTRA', 'CSX', 'CVS', 'DHI', 'DHR', 'DE', 'DAL', 'DVN', 'DLR', 'DFS', 'DISH', 'DIS', 'DG', 'DLTR', 'DPZ', 'DOW', 'DD', 'EBAY', 'EA', 'ELV', 'LLY', 'EMR', 'ENPH', 'EOG', 'EQT', 
'ETSY', 'EXPE', 'XOM', 'FDX', 'FITB', 'FSLR', 'FI', 'F', 'FTNT', 'FOXA', 'FCX', 'GEHC', 'GNRC', 'GD', 'GE', 'GM', 'GILD', 'GS', 'HAL', 'HSY', 'HES', 'HD', 'HON', 'HRL', 'HPQ', 'HUM', 'HBAN', 'IBM', 'ILMN', 
'INTC', 'IP', 'INTU', 'ISRG', 'JNJ', 'JPM', 'JNPR', 'KEY', 'KMB', 'KMI', 'KLAC', 'KHC', 'KR', 'LRCX', 'LVS', 'LEN', 'LMT', 'LOW', 'MRO', 'MPC', 'MAR', 'MA', 'MTCH', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 
'MGM', 'MU', 'MSFT', 'MRNA', 'MDLZ', 'MS', 'MOS', 'NTAP', 'NFLX', 'NEM', 'NKE', 'NSC', 'NOC', 'NCLH', 'NUE', 'NVDA', 'NXPI', 'OXY', 'ON', 'ORCL', 'PARA', 'PYPL', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PXD', 'PNC', 
'PPG', 'PG', 'PHM', 'QCOM', 'RTX', 'REGN', 'ROST', 'RCL', 'SPGI', 'CRM', 'SLB', 'STX', 'NOW', 'SWKS', 'SEDG', 'SO', 'LUV', 'SBUX', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TGT', 'TSLA', 'TXN', 'TMO', 'TJX', 'TSCO', 'TFC', 
'TSN', 'USB', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'VLO', 'VZ', 'VRTX', 'VFC', 'V', 'WBA', 'WMT', 'WBD', 'WM', 'WFC', 'WDC', 'WHR', 'WMB', 'WYNN', 'ZION','LYFT', 'UBER', 'SNOW', 'ZM', 'TWLO', 'PTON', 'SOFI', 
'DKNG', 'NET', 'TTD', 'OKTA', 'ARM', 'CRWD', 'GIS', 'W', 'PINS', 'MARA', 'PLTR', 'ZS', 'ABNB', 'DOCU', 'TDOC', 'SHOP', 'TEAM', 'TSM', 'SQ', 'PANW', 'DDOG',"QQQ","SPY","IWM"]

UNDESIRABLES = ['COIN','BILI','UPST','CVNA',"TQQQ","SQQQ","SPXS","SPXL","SOXL","SOXS","NIO","BABA","ROKU","RBLX",
                "SE","SNAP","LCID",'RIVN',"BIDU","FUTU","TSLA","JD","HOOD","CHWY","CMG","NFLX","AVGO","BKNG","ABNB","MARA"]

BF3 = [
    'QQQ','SPY','IWM','ADBE', 'GOOGL', 'GOOG', 'AMZN', 'AMD', 
    'AXP', 'AAPL', 'BAC', 'BA', 'CVX', 'CSCO', 'C', 'DIS', 'XOM', 
    'GM', 'INTC', 'JPM', 'MSFT', 'NFLX', 'NVDA', 'PYPL', 
    'TSLA', 'V', 'SQ', 'TSM', 'DOCU', 'UBER', 'SNOW', 'PLTR', 'ABNB','AVGO',
    # "FB"
    'META'
    ]


TRADING_SYMBOLS =  [
                    'ZM', 'UBER', 'CMG', 
                    'AXP', 'TDOC', 'UAL', 'DAL', 'MMM', 'PEP', 'GE', 'RCL', 'MRK',
 'HD', 'LOW', 'VZ', 'PG', 'TSM', 'GOOG', 'GOOGL', 'AMZN', 'BAC', 'AAPL', 'ABNB',
 'CRM', 'MSFT', 'F', 'V', 'MA', 'JNJ', 'DIS', 'JPM', 'ADBE', 'BA', 'CVX', 'PFE',
 'META', 'C', 'CAT', 'KO', 'MS', 'GS', 'IBM', 'CSCO', 'WMT','WFC',
 'TGT', 'COST', 'SQ', 'SHOP', 'DOCU','TWLO', 'DDOG', 'ZS', 'NET',
 'OKTA','ETSY', 'PINS','AMD',
 'NVDA', 'PYPL', 'PLTR', 'NFLX', 'CRWD', 'INTC', 'MRNA', 'SNOW', 'SOFI', 'PANW',
 'ORCL','SBUX','NKE','TSLA','XOM',"RTX","UPS","FDX","CAT","PG","COST","LMT","GS","MS",
 "AXP","GIS","KHC","W","CHWY","PTON","DOCU","TTD","NOW","TEAM","MDB","HOOD","MARA","AI",
 "LYFT","BYND", 'AVGO', 'QCOM', 'AAL', 'CZR', 'ARM', 'DKNG', 'NCLH', 
'MU', 'WBD', 'CCL', 'AMAT', 'TXN', 'SNAP', 'MGM', 'CVNA','MCD','AVGO','GM','DG','DE','BKNG',
 'INTU','ADSK','WDAY','SPOT','LCRX']

TREND_SYMBOLS =  ['ZM', 'UBER', 'CMG', 'AXP', 'TDOC', 'UAL', 'DAL', 'MMM', 'PEP', 'GE', 'RCL', 'MRK',
 'HD', 'LOW', 'VZ', 'PG', 'TSM', 'GOOG', 'GOOGL', 'AMZN', 'BAC', 'AAPL',
 'CRM', 'MSFT', 'F', 'V', 'MA', 'JNJ', 'DIS', 'JPM', 'ADBE', 'BA', 'CVX', 'PFE',
 'META', 'C', 'CAT', 'KO', 'MS', 'GS', 'IBM', 'CSCO', 'WMT','WFC',
 'TGT', 'COST', 'SQ', 'SHOP', 'DOCU','TWLO', 'DDOG', 'ZS', 'NET',
 'OKTA','ETSY', 'PINS','AMD',
 'NVDA', 'PYPL', 'PLTR', 'CRWD', 'INTC', 'MRNA', 'SNOW', 'SOFI', 'PANW',
 'ORCL','SBUX','NKE','XOM',"RTX","UPS","FDX","CAT","PG","COST","LMT","GS","MS",
 "AXP","GIS","KHC","W","PTON","DOCU","TTD","NOW","TEAM","MDB",
 "LYFT","BYND", 'AVGO', 'QCOM', 'AAL', 'CZR', 'ARM', 'DKNG', 'NCLH', 
 'MU', 'WBD', 'CCL', 'AMAT', 'TXN', 'MGM','MCD','GM','DG','DE',
 'INTU','ADSK','WDAY','SPOT','LCRX']

FULL_SYM = ['VUG', 'IWF', 'IJH', 'IJR', 'VGT', 'VO', 'XLK', 'VB', 'XLE', 'MMM', 'AOS', 'ABT', 'ACN', 'ADM', 'ADBE', 'ADP', 'AAP', 'AES', 'AFL', 'A', 'APD', 
'AKAM', 'ALK', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'AMZN', 'AMCR', 'AMD', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 
'AWK', 'AMP', 'ABC', 'AME', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'AZO',
'AVB', 'AVY', 'AXON', 'BKR', 'BAC', 'BBWI', 'BAX', 'BDX', 'WRB', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 
'AVGO', 'BR', 'BRO', 'BF.B', 'BG', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW',
                'CE', 'CNC', 'CNP', 'CDAY', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'CTSH',
                  'CMCSA', 'CMA', 'COP', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 
                  'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISH', 'DIS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DD', 'DXC', 'EMN',
                    'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'RE', 'EVRG', 
                    'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FITB', 'FSLR', 'FE', 'FIS', 'FLT', 'FMC', 'F', 'FTNT', 'FTV',
                      'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GNRC', 'GE', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HES', 
                      'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HST', 'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IEX', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 
                      'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JKHY', 'J', 'JCI', 'JPM', 'JNPR', 'KEY', 'KEYS', 'KIM', 'KMI', 'KLAC',
                        'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR',
                          'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCK', 'MDT', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MPWR',
                            'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 
                            'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OGN', 'OTIS', 'PCAR', 'PKG', 'PH', 
                            'PAYX', 'PAYC', 'PYPL', 'PNR', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC',
                              'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RMD', 'RHI', 'ROK', 'ROL', 'ROP', 
                              'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SNA', 'SEDG', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 
                              'STLD', 'STE', 'SYK', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 
                              'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 
                              'VFC', 'VTRS', 'VICI', 'V', 'VMC', 'WAB', 'WBA', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WRK', 'WY', 'WHR', 'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH',
                                'ZION', 'ZTS', 'CHWY', 'TEAM', 'HOOD', 'DOCU', 'TTD', 'UBER', 'JD', 'DDOG', 'CRWD', 'SQ', 'FUTU', 'TSM', 'TDOC', 'SNOW', 'BIDU', 'OKTA', 'ZM', 'WBD', 'TWLO', 'ZS', 'BABA', 'PLTR',
                                  'PINS', 'PANW', 'ABNB', 'ARM']

MODEL_FEATURES = {
    "GAIN": ['oneD_stddev50', 'rsi', 'close_diff', 'daily_volume_vol_diff_pct30', 'range_vol_diff5', 'SPY_diff', 'threeD_stddev50', 'close_diff3', 'min_volume_vol_diff_pct', 'month', 
            'return_vol_240M', 'range_vol', 'rsi5', 'roc', 'SPY_3D', 'roc5', 'roc_diff', 'price_25DDiff', 'daily_volume_vol_diff_pct', 'price_10DDiff', 'SPY_1D', 'hour_volume_vol_diff', 
            'hour_volume_vol_diff_pct', 'return_vol_10D', 'SPY_5D'],
    "GAIN_1D": ['range_vol', 'day_of_week', 'adx', 'daily_volume_vol_diff_pct30', 'roc', 'daily_vol_diff', 'SPY_diff5', 
               'return_vol_16H', 'SPY_3D', 'rsi3', 'close_diff5', 'rsi5', 'min_vol_diff', 'volume_vol_8H', 'SPY_diff', 
               'rsi', 'hour_volume_vol_diff', 'daily_vol_diff_pct30', 'return_vol_10D', 'roc3', 'price_25DDiff', 
               'daily_volume_vol_diff_pct', 'return_vol_240M', 'SPY_diff3', 'month'],
    "GAINP": ['return_vol_450M', 'return_vol_16H', 'min_volume_vol_diff_pct', 'price_25DDiff', 'range_vol', 'SPY_1D', 'rsi', 'SPY_diff', 'return_vol_8H', 
            'min_vol_diff', 'daily_volume_vol_diff_pct', 'hour_volume_vol_diff', 'hour_volume_vol_diff_pct', 'daily_vol_diff', 'price_10DDiff', 
            'threeD_stddev50', 'month', 'close_diff3', 'roc5', 'close_diff', 'roc_diff', 'roc3', 'range_vol_diff5', 
            'SPY_5D', 'SPY_diff5', 'daily_vol_diff_pct30', 'adx', 'close_diff_deviation', 'price7', 'volume_vol_8H', 'return_vol_240M', 
            'SPY_diff3', 'daily_volume_vol_diff_pct30', 'SPY_3D', 'volume_vol_16H'],
    "GAINP_1D": ['month', 'rsi5', 'volume_vol_8H', 'SPY_diff', 'daily_volume_vol_diff_pct', 'roc3', 'hour_volume_vol_diff_pct', 'SPY_diff5', 'range_vol', 
            'price_10DDiff', 'close_diff', 'SPY_5D', 'return_vol_8H', 'return_vol_240M', 'daily_volume_vol_diff_pct30', 'min_volume_vol_diff_pct', 'close_diff5',
            'daily_vol_diff_pct30', 'price_25DDiff', 'range_vol_diff5', 'hour_volume_vol_diff', 'rsi'],
    "LOSERS": ['adx', 'close_diff3', 'roc', 'range_vol_diff5', 'close_diff_deviation', 'min_volume_vol_diff_pct', 'min_vol_diff', 'roc5', 'daily_vol_diff_pct30', 
            'day_of_week', 'rsi', 'SPY_diff', 'SPY_diff3', 'daily_vol_diff_pct', 'hour_volume_vol_diff', 'return_vol_240M', 'close_diff', 'daily_volume_vol_diff_pct30', 'price_10DDiff', 'SPY_3D', 
            'volume_vol_8H', 'SPY_diff5', 'return_vol_16H', 'hour', 'month', 'oneD_stddev50', 'SPY_1D', 'price_25DDiff', 'rsi5', 'daily_vol_diff', 'roc_diff', 'return_vol_450M', 'range_vol', 
            'close_diff5', 'return_vol_8H'],
    "LOSERS_1D": ['adx', 'daily_vol_diff_pct30', 'return_vol_450M', 'range_vol', 'roc5', 'range_vol_diff5', 'day_of_week', 'close_diff_deviation', 'SPY_diff3', 
            'price_10DDiff', 'SPY_1D', 'min_volume_vol_diff_pct', 'return_vol_240M', 'month', 'close_diff', 'roc', 'SPY_3D', 'hour_volume_vol_diff_pct', 
            'daily_vol_diff30', 'oneD_stddev50', 'SPY_diff5', 'threeD_stddev50', 'daily_volume_vol_diff_pct', 'roc_diff', 'price7', 'min_vol_diff', 
            'daily_volume_vol_diff_pct30', 'return_vol_10D', 'SPY_diff'],
    "LOSERSC": ['price7', 'price_10DDiff', 'daily_vol_diff30', 'SPY_diff3', 'daily_vol_diff_pct30', 'hour_volume_vol_diff', 'hour_volume_vol_diff_pct', 
            'day_of_week', 'SPY_1D', 'volume_vol_8H', 'daily_vol_diff_pct', 'SPY_diff5', 'return_vol_10D', 'month', 'return_vol_240M', 'rsi3', 
            'range_vol_diff5', 'daily_volume_vol_diff_pct30', 'rsi5', 'roc', 'daily_vol_diff', 'return_vol_450M', 'hour', 'rsi', 'SPY_5D',
            'min_volume_vol_diff_pct', 'adx', 'SPY_diff'],
    "LOSERSC_1D": ['daily_volume_vol_diff_pct', 'daily_vol_diff30', 'rsi', 'close_diff', 'roc5', 'price7', 'month', 'return_vol_8H', 'return_vol_16H', 'roc_diff', 
            'return_vol_450M', 'hour_volume_vol_diff_pct', 'oneD_stddev50', 'daily_volume_vol_diff_pct30', 'rsi3', 'price_10DDiff', 'rsi5', 
            'daily_vol_diff_pct30', 'roc', 'volume_vol_8H', 'return_vol_10D'],
    "MA": ['range_vol_diff5', 'price_10DDiff', 'return_vol_450M', 'SPY_diff3', 'close_diff_deviation', 'roc5', 'hour_volume_vol_diff', 
            'return_vol_240M', 'SPY_1D', 'hour_volume_vol_diff_pct', 'return_vol_16H', 'min_volume_vol_diff_pct', 'hour', 'SPY_diff', 
            'close_diff3', 'month', 'roc_diff', 'range_vol', 'daily_vol_diff', 'daily_volume_vol_diff_pct', 'SPY_5D', 'roc3', 'oneD_stddev50', 
            'roc', 'daily_vol_diff_pct', 'day_of_week', 'daily_vol_diff_pct30', 'daily_volume_vol_diff_pct30', 'close_diff', 'rsi5', 'return_vol_10D', 'daily_vol_diff30'],
    "MA_1D": ['price_10DDiff', 'range_vol', 'return_vol_8H', 'min_vol_diff_pct', 'daily_vol_diff30', 'volume_vol_10D', 'oneD_returns_close', 'hour_volume_vol_diff_pct', 
            'volume_10MA', 'oneD_stddev50', 'vol7', 'min_volume_vol_diff_pct', 'rsi5', 'month', 'return_vol_30D', 'threeD_stddev50', 'range_vol_diff5', 'return_vol_10D', 
            'day_of_month', 'v_diff_pct', 'hour_vol_diff_pct', 'daily_volume_vol_diff', 'hour', 'day_of_week', 'close_diff_deviation3', 'volume_vol_240M', 'roc', 'adx', 
            'close_diff', 'price_25DDiff', 'close_diff3', 'rsi3', 'range_vol10MA', 'roc5', 'daily_vol_diff', 'min_vol_diff', 'daily_volume_vol_diff30'],
    "MAP": ['SPY_3D', 'oneD_stddev50', 'hour', 'SPY_diff3', 'SPY_5D', 'volume_vol_8H', 'return_vol_450M', 'return_vol_8H', 'daily_vol_diff_pct', 
            'return_vol_10D', 'range_vol', 'daily_vol_diff_pct30', 'return_vol_240M', 'price_25DDiff', 'price7',
            'close_diff_deviation', 'min_vol_diff', 'adx', 'hour_volume_vol_diff', 'min_volume_vol_diff_pct', 'month', 'volume_vol_16H',
            'roc_diff', 'day_of_week', 'range_vol_diff5', 'close_diff3'],
    "MAP_1D": ['close_diff_deviation', 'SPY_diff5', 'day_of_week', 'return_vol_10D', 'SPY_5D', 'SPY_1D', 'hour_volume_vol_diff_pct', 'hour_volume_vol_diff', 'roc', 
            'range_vol_diff5', 'close_diff5', 'min_vol_diff', 'SPY_diff', 'daily_vol_diff_pct30', 'SPY_3D', 'daily_volume_vol_diff_pct30', 'return_vol_16H', 'price7', 
            'rsi5', 'rsi', 'daily_vol_diff', 'rsi3', 'threeD_stddev50', 'month', 'oneD_stddev50', 'roc5', 'roc3', 'volume_vol_16H', 'roc_diff', 'hour', 'daily_volume_vol_diff_pct', 
            'daily_vol_diff30', 'range_vol'],
    "CDBFP": ['return_vol_8H', 'close_diff_deviation3', 'SPY_diff5', 'volume_vol_8H', 'return_vol_10D', 'range_vol_diff5', 'min_vol_diff_pct', 'range_vol10MA', 
            'vol7', 'daily_volume_vol_diff30', 'day_of_week', 'SPY_1D', 'oneD_returns_close', 'daily_vol_diff', 'roc_diff', 'volume_vol_5D', 'volume_vol_450M', 
            'rsi', 'volume_vol_15M', 'threeD_stddev50', 'range_vol25MA', 'month', 'volume_vol_240M','cd_vol','cd_vol3'],
    "CDBFP_1D": ['volume_vol_60M', 'hour_vol_diff', 'range_vol10MA', 'hour_volume_vol_diff_pct', 'close_diff_deviation3', 'threeD_returns_close', 'volume_10DDiff', 
            '15min_vol_diff', 'close_diff', 'month', 'close_diff_deviation', 'volume_vol_8H', 'return_vol_4H', 'roc3', 'range_vol5MA', 'roc_diff', 'volume_25DDiff', 
            'rsi5', 'price7', 'adx', 'threeD_stddev50', 'day_of_week', 'return_vol_8H', 'min_volume_vol_diff_pct', 'range_vol25MA', 'oneD_returns_close', 'roc5', 'close_diff3', 
            'hour_vol_diff_pct', 'return_vol_120M', 'vol14', 'volume_vol_30M', 'return_vol_5D', 'daily_vol_diff_pct', 'daily_vol_diff30', 'return_vol_10D', 
            'volume_vol_10D', 'price14', 'hour', 'vol7','cd_vol','cd_vol3'],
    "CDBFC": ['return_vol_5D', 'volume_10DDiff', 'oneD_stddev50', 'rsi', 'volume_vol_16H', 'return_vol_8H', 'min_volume_vol_diff', 'roc3', 'daily_vol_diff30', 
            'return_vol_3D', 'daily_vol_diff_pct30', 'hour_volume_vol_diff_pct', 'SPY_5D', 'hour_vol_diff_pct', 'volume_vol_10D', 'daily_volume_vol_diff_pct30', 
            'range_vol5MA', 'volume_vol_60M', 'SPY_diff3', 'month', 'vol7', 'range_vol', 'hour_volume_vol_diff', 'roc_diff', 'range_vol_diff5', 'return_vol_120M', 
            'close_diff', 'daily_volume_vol_diff', 'SPY_3D', 'volume_vol_30M', 'vol14', 'daily_vol_diff_pct'],
    "CDBFC_1D": ['close_diff5', 'return_vol_30D', 'day_of_week', 'close_diff_deviation3', 'volume_vol_5D', 'SPY_diff3', 'oneD_returns_close', 'month', 'rsi', 
            'volume_vol_15M', 'min_volume_vol_diff', 'volume_vol_30M', 'roc3', 'min_vol_diff_pct', 'return_vol_15M', 'range_vol5MA', 'volume_10DDiff', 'SPY_5D', 
            'return_vol_60M', 'close_diff3', 'volume_vol_30D', 'price_25DDiff', 'hour_vol_diff_pct', 'close_diff_deviation', 'return_vol_5D', 'return_vol_8H', 
            'return_vol_3D', 'daily_vol_diff_pct', 'rsi3', 'vol14', 'min_volume_vol_diff_pct','cd_vol','cd_vol3'],
}

ENDPOINT_NAMES = {
"GAIN": "invalerts-xgb-GAIN-classifier",
"GAIN_1D": "invalerts-xgb-GAIN-1D-classifier",
"GAINP": "invalerts-xgb-GAINP-classifier",
"GAINP_1D": "invalerts-xgb-GAINP-1D-classifier",
"LOSERS": "invalerts-xgb-LOSERS-classifier",
"LOSERS_1D": "invalerts-xgb-LOSERS-1D-classifier",
"LOSERSC": "invalerts-xgb-LOSERSC-classifier",
"LOSERSC_1D": "invalerts-xgb-LOSERSC-1D-classifier",
"MA": "invalerts-xgb-MA-classifier",
"MA_1D": "invalerts-xgb-MA-1D-classifier",
"MAP": "invalerts-xgb-MAP-classifier",
"MAP_1D": "invalerts-xgb-MAP-1D-classifier",
"CDBFC": "invalerts-xgb-CDBFC-classifier",
"CDBFC_1D": "invalerts-xgb-CDBFC-1D-classifier", 
"CDBFP": "invalerts-xgb-CDBFP-classifier",
"CDBFP_1D": "invalerts-xgb-CDBFP-1D-classifier",
}

UNDESIRABLES = ['COIN','BILI','UPST','CVNA',"TQQQ","SQQQ","SPXS","SPXL","SOXL","SOXS","NIO","BABA","ROKU","RBLX","SE","SNAP","LCID",'RIVN',"BIDU","FUTU","TSLA","JD","HOOD","CHWY","CMG","NFLX","AVGO","BKNG","ABNB"]

ALGORITHM_CONFIG = {
    "GAIN_1D": {
        "target_label": "one_max",
        "target_value": .016,
    },
    "GAIN": {
        "target_label": "three_max",
        "target_value": .026,
    },
    "GAINP_1D": {
        "target_label": "one_min",
        "target_value": -.01,
    },
    "GAINP": {
        "target_label": "three_min",
        "target_value": -.026,
    },
     "LOSERSC_1D": {
        "target_label": "one_max",
        "target_value": .02,
    },
    "LOSERSC": {
        "target_label": "three_max",
        "target_value": .031,
    },
    "LOSERS_1D": {
        "target_label": "one_min",
        "target_value": -.02,
    },
    "LOSERS": {
        "target_label": "three_min",
        "target_value": -.031,
    },
     "MA_1D": {
        "target_label": "one_max",
        "target_value": .017,
    },
    "MA": {
        "target_label": "three_max",
        "target_value": .026,
    },
    "MAP_1D": {
        "target_label": "one_min",
        "target_value": -.017,
    },
    "MAP": {
        "target_label": "three_min",
        "target_value": -.026,
    },
    "CDBFC": {
        "target_label": "three_max_vol",
        "target_value": 1.731,
    },
    "CDBFP": {
        "target_label": "three_min_vol",
        "target_value": -1.554,
        
    },
    "CDBFC_1D": {
        "target_label": "one_max_vol",
        "target_value": 1.098,
    },
    "CDBFP_1D": {
        "target_label": "one_min_vol",
        "target_value": -1.012,
    },
}