ALL_SYM = ['SPY', 'IVV', 'VOO', 'VTI', 'QQQ', 'VEA', 'IEFA', 'VTV', 'BND', 'AGG', 'VUG', 'VWO', 'IEMG', 'IWF', 'VIG', 
'IJH', 'IJR', 'GLD', 'VGT', 'VXUS', 'VO', 'IWM', 'BNDX', 'EFA', 'IWD', 'VYM', 'SCHD', 'XLK', 'ITOT', 'VB', 'VCIT', 
'XLV', 'TLT', 'BSV', 'VCSH', 'LQD', 'XLE', 'VEU', 'RSP', 'TQQQ', 'SQQQ', 'SPXS', 'SPXL', 'SOXL', 'SOXS', 'MMM', 'AOS', 
'ABT', 'ABBV', 'ACN', 'ATVI', 'ADM', 'ADBE', 'ADP', 'AAP', 'AES', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALGN', 
'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AMD', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 
'ABC', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 
'ADSK', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BAC', 'BBWI', 'BAX', 'BDX', 'WRB', 'BRK.B', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 
'BK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'BG', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 
'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'CNC', 'CNP', 'CDAY', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 
'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'COP', 
'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 
'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISH', 'DIS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DD', 'DXC', 'EMN', 
'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 
'ETSY', 'RE', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 
'FITB', 'FSLR', 'FE', 'FIS', 'FLT', 'FMC', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GNRC', 
'GD', 'GE', 'GIS', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HSY', 'HES', 
'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 
'ILMN', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 
'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KLAC', 'KHC', 'KR', 'LHX', 
'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MRO', 'MPC', 
'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 
'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 
'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 
'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OGN', 'OTIS', 'PCAR', 'PKG', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 
'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 
'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'ROL', 
'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SNA', 
'SEDG', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 
'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 
'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VRSN', 
'VRSK', 'VZ', 'VRTX', 'VFC', 'VTRS', 'VICI', 'V', 'VMC', 'WAB', 'WBA', 'WMT', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 
'WST', 'WDC', 'WRK', 'WY', 'WHR', 'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZION', 'ZTS', 
'CVNA', 'DKNG', 'VXX', 'W', 'CHWY', 'PTON', 'TEAM', 'MDB', 'HOOD', 'MARA', 'AI', 'LYFT', 'BYND', 'RIOT', 'U', 'DOCU', 'TTD',
'UBER', 'JD', 'DDOG', 'CRWD', 'SQ', 'RBLX', 'SNAP', 'FUTU', 'TSM', 'LCID', 'UPST', 'TDOC', 'SNOW', 'BIDU', 'NIO', 'SHOP', 'ROKU', 
'OKTA', 'RIVN', 'ZM', 'WBD', 'SE', 'SOFI', 'META', 'TWLO', 'ZS', 'BABA', 'PLTR', 'PINS', 'PANW', 'ABNB', 'NET', 'COIN', 'BILI', 'ARM']

WEEKLY_EXP = ['MMM', 'ABT', 'ABBV', 'ACN', 'ATVI', 'ADM', 'ADBE', 'ADP', 
'AAP', 'AFL', 'ALB', 'ALGN', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMD', 'AAL', 'AXP', 'AIG', 'ABC', 'AMGN', 'ADI', 'APA', 'AAPL', 'AMAT', 'ANET', 'T', 'ADSK', 'BAC', 'BBWI', 'BAX', 'BBY', 'BIIB', 
'BLK', 'BA', 'BKNG', 'BMY', 'AVGO', 'CZR', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CAT', 'CBOE', 'CNC', 'CF', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CI', 'CSCO', 'C', 'CLX', 'CME', 'KO', 'CMCSA', 'CMA', 'CAG', 
'COP', 'STZ', 'GLW', 'COST', 'CTRA', 'CSX', 'CVS', 'DHI', 'DHR', 'DE', 'DAL', 'DVN', 'DLR', 'DFS', 'DISH', 'DIS', 'DG', 'DLTR', 'DPZ', 'DOW', 'DD', 'EBAY', 'EA', 'ELV', 'LLY', 'EMR', 'ENPH', 'EOG', 'EQT', 
'ETSY', 'EXPE', 'XOM', 'FDX', 'FITB', 'FSLR', 'FI', 'F', 'FTNT', 'FOXA', 'FCX', 'GEHC', 'GNRC', 'GD', 'GE', 'GM', 'GILD', 'GS', 'HAL', 'HSY', 'HES', 'HD', 'HON', 'HRL', 'HPQ', 'HUM', 'HBAN', 'IBM', 'ILMN', 
'INTC', 'IP', 'INTU', 'ISRG', 'JNJ', 'JPM', 'JNPR', 'KEY', 'KMB', 'KMI', 'KLAC', 'KHC', 'KR', 'LRCX', 'LVS', 'LEN', 'LMT', 'LOW', 'MRO', 'MPC', 'MAR', 'MA', 'MTCH', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 
'MGM', 'MU', 'MSFT', 'MRNA', 'MDLZ', 'MS', 'MOS', 'NTAP', 'NFLX', 'NEM', 'NKE', 'NSC', 'NOC', 'NCLH', 'NUE', 'NVDA', 'NXPI', 'OXY', 'ON', 'ORCL', 'PARA', 'PYPL', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PXD', 'PNC', 
'PPG', 'PG', 'PHM', 'QCOM', 'RTX', 'REGN', 'ROST', 'RCL', 'SPGI', 'CRM', 'SLB', 'STX', 'NOW', 'SWKS', 'SEDG', 'SO', 'LUV', 'SBUX', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TGT', 'TSLA', 'TXN', 'TMO', 'TJX', 'TSCO', 'TFC', 
'TSN', 'USB', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'VLO', 'VZ', 'VRTX', 'VFC', 'V', 'WBA', 'WMT', 'WBD', 'WM', 'WFC', 'WDC', 'WHR', 'WMB', 'WYNN', 'ZION','LYFT', 'UBER', 'SNOW', 'ZM', 'TWLO', 'PTON', 'SOFI', 
'DKNG', 'NET', 'TTD', 'OKTA', 'ARM', 'CRWD', 'GIS', 'W', 'PINS', 'MARA', 'PLTR', 'ZS', 'ABNB', 'DOCU', 'TDOC', 'SHOP', 'TEAM', 'TSM', 'SQ', 'PANW', 'DDOG']


TRADING_SYMBOLS =  [
#   'ZM', 'UBER', 'CMG', 'AXP', 'TDOC', 'UAL', 'DAL', 'MMM', 'PEP', 'GE', 'RCL', 'MRK',
#  'HD', 'LOW', 'VZ', 'PG', 'TSM', 'GOOG', 'GOOGL', 'AMZN', 'BAC', 'AAPL', 'ABNB',
#  'CRM', 'MSFT', 'F', 'V', 'MA', 'JNJ', 'DIS', 'JPM', 'ADBE', 'BA', 'CVX', 'PFE',
#  'META', 'C', 'CAT', 'KO', 'MS', 'GS', 'IBM', 'CSCO', 'WMT','TSLA','LCID','NIO','WFC',
#  'TGT', 'COST', 'RIVN', 'COIN', 'SQ', 'SHOP', 'DOCU', 'ROKU', 'TWLO', 'DDOG', 'ZS', 'NET',
#  'OKTA', 'UPST', 'ETSY', 'PINS', 'FUTU', 'SE', 'BIDU', 'JD', 'BABA', 'RBLX', 'AMD',
#  'NVDA', 'PYPL', 'PLTR', 'NFLX', 'CRWD', 'INTC', 'MRNA', 'SNOW', 'SOFI', 'PANW',
#  'ORCL','SBUX','NKE','TSLA','XOM',"RTX","UPS","FDX","CAT","PG","COST","LMT","GS","MS",
#  "AXP","GIS","KHC","W","CHWY","PTON","DOCU","TTD","NOW","TEAM","MDB",
#  "HOOD","MARA","AI", "BYND",
#  "LYFT",'AVGO', 'QCOM', 'AAL', 'CZR', 'ARM', 'DKNG', 'NCLH', 
# 'MU', 'WBD', 'CCL', 'AMAT', 'TXN', 'SNAP', 'MGM', 'CVNA','MCD','GM','DG','DE', 'BKNG'
    "TEAM","NOW","FDX","TTD","UPS"]

FULL_SYM = ['VUG', 'IWF', 'IJH', 'IJR', 'VGT', 'VO', 'XLK', 'VB', 'XLE', 'MMM', 'AOS', 'ABT', 'ACN', 'ADM', 'ADBE', 'ADP', 'AAP', 'AES', 'AFL', 'A', 'APD', 
'AKAM', 'ALK', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'AMZN', 'AMCR', 'AMD', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 
'AWK', 'AMP', 'ABC', 'AME', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'AZO',
'AVB', 'AVY', 'AXON', 'BKR', 'BAC', 'BBWI', 'BAX', 'BDX', 'WRB', 'BBY', 'BIO', 'TECH', 'BIIB', 'BLK', 'BK', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 
'AVGO', 'BR', 'BRO', 'BF.B', 'BG', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW',
                'CE', 'CNC', 'CNP', 'CDAY', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'CTSH',
                  'CMCSA', 'CMA', 'COP', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 
                  'DE', 'DAL', 'XRAY', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DISH', 'DIS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DTE', 'DUK', 'DD', 'DXC', 'EMN',
                    'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'LLY', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ETSY', 'RE', 'EVRG', 
                    'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FITB', 'FSLR', 'FE', 'FIS', 'FLT', 'FMC', 'F', 'FTNT', 'FTV',
                      'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GNRC', 'GE', 'GM', 'GPC', 'GILD', 'GL', 'GPN', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'PEAK', 'HSIC', 'HES', 
                      'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HST', 'HWM', 'HPQ', 'HUM', 'HBAN', 'HII', 'IEX', 'IDXX', 'ITW', 'ILMN', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 
                      'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JKHY', 'J', 'JCI', 'JPM', 'JNPR', 'KEY', 'KEYS', 'KIM', 'KMI', 'KLAC',
                        'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LNC', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR',
                          'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCK', 'MDT', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MPWR',
                            'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NWL', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 
                            'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OGN', 'OTIS', 'PCAR', 'PKG', 'PH', 
                            'PAYX', 'PAYC', 'PYPL', 'PNR', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC',
                              'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RMD', 'RHI', 'ROK', 'ROL', 'ROP', 
                              'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SEE', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SNA', 'SEDG', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 
                              'STLD', 'STE', 'SYK', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 
                              'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 
                              'VFC', 'VTRS', 'VICI', 'V', 'VMC', 'WAB', 'WBA', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WRK', 'WY', 'WHR', 'WMB', 'WTW', 'GWW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH',
                                'ZION', 'ZTS', 'CHWY', 'TEAM', 'HOOD', 'DOCU', 'TTD', 'UBER', 'JD', 'DDOG', 'CRWD', 'SQ', 'FUTU', 'TSM', 'TDOC', 'SNOW', 'BIDU', 'OKTA', 'ZM', 'WBD', 'TWLO', 'ZS', 'BABA', 'PLTR',
                                  'PINS', 'PANW', 'ABNB', 'ARM']

MODEL_FEATURES = {
    "GAIN": ['hour', 'daily_vol_diff30', 'hour_volume_vol_diff', 'roc_diff', 'range_vol', 'volume_vol_8H', 'month', 
            'close_diff5', 'range_vol_diff5', 'SPY_diff', 'return_vol_10D', 'return_vol_8H', 'return_vol_450M', 'adx', 
            'rsi', 'daily_vol_diff', 'SPY_3D', 'min_vol_diff', 'return_vol_240M', 'price_25DDiff', 'daily_vol_diff_pct30',
              'price7', 'daily_vol_diff_pct', 'oneD_stddev50', 'volume_vol_16H', 'close_diff_deviation'],
    "GAIN_1D": ['roc', 'daily_vol_diff30', 'volume_vol_5D', 'volume_vol_16H', 'return_vol_10D', 'return_vol_30D', 'month', 
            'oneD_stddev50', 'close_diff', 'min_vol_diff_pct', 'volume_vol_450M', 'adx', 'hour_vol_diff_pct', 'price_25DDiff', 
            'hour_vol_diff', 'min_vol_diff', 'price_10DDiff', 'range_vol', 'daily_vol_diff_pct', 'v_diff_pct', 'hour_volume_vol_diff',
              'rsi', 'close_diff_deviation3', 'SPY_3D'],
    "GAINP": ['volume_vol_240M', 'hour', 'volume_vol_16H', 'daily_vol_diff_pct30', 'daily_vol_diff_pct', 'return_vol_30D', 'daily_volume_vol_diff', 'range_vol_diff5', 'volume_vol_10D', 
                                        'close_diff_deviation3', 'daily_volume_vol_diff_pct30', 'price7', 'threeD_stddev50', 'v_diff_pct', 'volume_vol_450M', 'month', 'roc5', 'oneD_stddev50', 'min_volume_vol_diff_pct', 
                                        'return_vol_450M', 'hour_volume_vol_diff', 'threeD_returns_close', 'daily_volume_vol_diff_pct', 'volume_vol_30D', 'day_of_month', 'hour_volume_vol_diff_pct', 'range_vol', 'price_10DDiff', 
                                        'roc_diff', 'return_vol_240M', 'roc3', 'min_volume_vol_diff', 'oneD_returns_close', 'return_vol_10D', 'return_vol_16H', 'daily_vol_diff', 'rsi', 'min_vol_diff_pct', 'hour_vol_diff_pct', 
                                        'day_of_week'],
    "GAINP_1D": ['volume_vol_30D', 'range_vol_diff5', 'daily_volume_vol_diff', 'roc3', 'return_vol_30D', 'volume_vol_8H', 'month', 
            'daily_volume_vol_diff_pct30', 'volume_vol_16H', 'day_of_month', 'return_vol_5D', 'hour_volume_vol_diff_pct', 'oneD_returns_close', 
            'threeD_returns_close', 'daily_vol_diff', 'close_diff3', 'range_vol', 'min_vol_diff', 'volume_vol_10D', 'cmf', 'daily_volume_vol_diff_pct', 
            'min_volume_vol_diff', 'price_25DDiff', 'return_vol_16H', 'hour_vol_diff', 'volume_vol_5D', 'close_diff', 'price_10DDiff', 'roc_diff', 
            'return_vol_8H', 'return_vol_10D', 'v_diff_pct', 'daily_volume_vol_diff30', 'roc', 'threeD_stddev50', 'volume_vol_240M', 'daily_vol_diff_pct', 
            'roc5', 'close_diff5', 'min_vol_diff_pct'],
    "LOSERS": ['return_vol_30D', 'threeD_stddev50', 'month', 'return_vol_450M', 'SPY_1D', 'oneD_returns_close',
             'min_volume_vol_diff_pct', 'price_10DDiff', 'oneD_stddev50', 'volume_vol_16H', 'min_volume_vol_diff', 
             'volume_vol_8H', 'daily_vol_diff_pct30', 'hour_vol_diff_pct', 'volume_vol_240M', 'SPY_diff', 'hour_volume_vol_diff',
               'volume_vol_30D', 'min_vol_diff_pct', 'return_vol_8H', 'hour', 'daily_vol_diff_pct', 'price_25DDiff', 'SPY_diff3', 
               'range_vol', 'rsi5', 'rsi', 'roc_diff', 'roc3', 'daily_volume_vol_diff', 'hour_vol_diff', 'return_vol_240M', 
               'close_diff', 'min_vol_diff'],
    "LOSERS_1D": ['volume_vol_240M', 'roc', 'volume_vol_450M', 'roc_diff', 'SPY_diff', 'daily_volume_vol_diff30', 'rsi5', 'SPY_1D', 
            'range_vol_diff5', 'day_of_week', 'hour_volume_vol_diff_pct', 'daily_vol_diff_pct30', 'roc5', 'close_diff5', 
            'volume_vol_16H', 'v_diff_pct', 'volume_vol_30D', 'cmf', 'month', 'volume_vol_8H', 'threeD_returns_close', 
            'daily_vol_diff_pct', 'return_vol_8H', 'return_vol_240M', 'oneD_stddev50', 'day_of_month', 'range_vol', 
            'price_10DDiff', 'hour_vol_diff_pct', 'daily_vol_diff30', 'hour', 'return_vol_16H', 'return_vol_450M', 
            'daily_volume_vol_diff_pct', 'min_volume_vol_diff', 'hour_vol_diff', 'SPY_diff3'],
    "LOSERSC": ['rsi', 'daily_volume_vol_diff_pct', 'v_diff_pct', 'hour_volume_vol_diff', 'close_diff3', 'threeD_returns_close', 'return_vol_10D', 'min_volume_vol_diff', 
                                           'hour', 'daily_volume_vol_diff', 'month', 'daily_vol_diff30', 'roc_diff', 'return_vol_16H', 'volume_vol_240M', 'min_vol_diff_pct', 'range_vol', 'oneD_returns_close', 
                                           'return_vol_30D', 'price_10DDiff', 'daily_volume_vol_diff30', 'day_of_week', 'volume_vol_16H', 'roc5'],
    "LOSERSC_1D": ['volume_vol_5D', 'price_10DDiff', 'volume_vol_10D', 'daily_vol_diff_pct30', 'range_vol', 'oneD_returns_close', 'day_of_month', 'volume_vol_30D', 'rsi', 'threeD_returns_close', 
                                           'range_vol_diff5', 'return_vol_10D', 'close_diff3', 'roc', 'daily_volume_vol_diff30', 'min_volume_vol_diff', 'return_vol_8H', 'return_vol_450M', 'daily_vol_diff', 'month',
                                             'close_diff', 'daily_volume_vol_diff_pct30', 'return_vol_30D', 'volume_vol_8H', 'volume_vol_16H', 'roc5', 'return_vol_240M', 'hour_vol_diff', 'cmf', 'min_vol_diff_pct', 'close_diff5'],
    "MA": ['hour', 'daily_vol_diff30', 'hour_volume_vol_diff', 'roc_diff', 'range_vol', 'volume_vol_8H', 'month', 
            'close_diff5', 'range_vol_diff5', 'SPY_diff', 'return_vol_10D', 'return_vol_8H', 'return_vol_450M', 'adx', 
            'rsi', 'daily_vol_diff', 'SPY_3D', 'min_vol_diff', 'return_vol_240M', 'price_25DDiff', 'daily_vol_diff_pct30',
              'price7', 'daily_vol_diff_pct', 'oneD_stddev50', 'volume_vol_16H', 'close_diff_deviation'],
    "MA_1D": ['roc', 'daily_vol_diff30', 'volume_vol_5D', 'volume_vol_16H', 'return_vol_10D', 'return_vol_30D', 'month', 
            'oneD_stddev50', 'close_diff', 'min_vol_diff_pct', 'volume_vol_450M', 'adx', 'hour_vol_diff_pct', 'price_25DDiff', 
            'hour_vol_diff', 'min_vol_diff', 'price_10DDiff', 'range_vol', 'daily_vol_diff_pct', 'v_diff_pct', 'hour_volume_vol_diff',
              'rsi', 'close_diff_deviation3', 'SPY_3D'],
    "MAP": ['volume_vol_240M', 'hour', 'volume_vol_16H', 'daily_vol_diff_pct30', 'daily_vol_diff_pct', 'return_vol_30D', 'daily_volume_vol_diff', 'range_vol_diff5', 'volume_vol_10D', 
                                        'close_diff_deviation3', 'daily_volume_vol_diff_pct30', 'price7', 'threeD_stddev50', 'v_diff_pct', 'volume_vol_450M', 'month', 'roc5', 'oneD_stddev50', 'min_volume_vol_diff_pct', 
                                        'return_vol_450M', 'hour_volume_vol_diff', 'threeD_returns_close', 'daily_volume_vol_diff_pct', 'volume_vol_30D', 'day_of_month', 'hour_volume_vol_diff_pct', 'range_vol', 'price_10DDiff', 
                                        'roc_diff', 'return_vol_240M', 'roc3', 'min_volume_vol_diff', 'oneD_returns_close', 'return_vol_10D', 'return_vol_16H', 'daily_vol_diff', 'rsi', 'min_vol_diff_pct', 'hour_vol_diff_pct', 
                                        'day_of_week'],
    "MAP_1D": ['volume_vol_30D', 'range_vol_diff5', 'daily_volume_vol_diff', 'roc3', 'return_vol_30D', 'volume_vol_8H', 'month', 
            'daily_volume_vol_diff_pct30', 'volume_vol_16H', 'day_of_month', 'return_vol_5D', 'hour_volume_vol_diff_pct', 'oneD_returns_close', 
            'threeD_returns_close', 'daily_vol_diff', 'close_diff3', 'range_vol', 'min_vol_diff', 'volume_vol_10D', 'cmf', 'daily_volume_vol_diff_pct', 
            'min_volume_vol_diff', 'price_25DDiff', 'return_vol_16H', 'hour_vol_diff', 'volume_vol_5D', 'close_diff', 'price_10DDiff', 'roc_diff', 
            'return_vol_8H', 'return_vol_10D', 'v_diff_pct', 'daily_volume_vol_diff30', 'roc', 'threeD_stddev50', 'volume_vol_240M', 'daily_vol_diff_pct', 
            'roc5', 'close_diff5', 'min_vol_diff_pct'],
    "VDIFFP": ['return_vol_30D', 'threeD_stddev50', 'month', 'return_vol_450M', 'SPY_1D', 'oneD_returns_close',
             'min_volume_vol_diff_pct', 'price_10DDiff', 'oneD_stddev50', 'volume_vol_16H', 'min_volume_vol_diff', 
             'volume_vol_8H', 'daily_vol_diff_pct30', 'hour_vol_diff_pct', 'volume_vol_240M', 'SPY_diff', 'hour_volume_vol_diff',
               'volume_vol_30D', 'min_vol_diff_pct', 'return_vol_8H', 'hour', 'daily_vol_diff_pct', 'price_25DDiff', 'SPY_diff3', 
               'range_vol', 'rsi5', 'rsi', 'roc_diff', 'roc3', 'daily_volume_vol_diff', 'hour_vol_diff', 'return_vol_240M', 
               'close_diff', 'min_vol_diff'],
    "VDIFFP_1D": ['volume_vol_240M', 'roc', 'volume_vol_450M', 'roc_diff', 'SPY_diff', 'daily_volume_vol_diff30', 'rsi5', 'SPY_1D', 
            'range_vol_diff5', 'day_of_week', 'hour_volume_vol_diff_pct', 'daily_vol_diff_pct30', 'roc5', 'close_diff5', 
            'volume_vol_16H', 'v_diff_pct', 'volume_vol_30D', 'cmf', 'month', 'volume_vol_8H', 'threeD_returns_close', 
            'daily_vol_diff_pct', 'return_vol_8H', 'return_vol_240M', 'oneD_stddev50', 'day_of_month', 'range_vol', 
            'price_10DDiff', 'hour_vol_diff_pct', 'daily_vol_diff30', 'hour', 'return_vol_16H', 'return_vol_450M', 
            'daily_volume_vol_diff_pct', 'min_volume_vol_diff', 'hour_vol_diff', 'SPY_diff3'],
    "VDIFFC": ['rsi', 'daily_volume_vol_diff_pct', 'v_diff_pct', 'hour_volume_vol_diff', 'close_diff3', 'threeD_returns_close', 'return_vol_10D', 'min_volume_vol_diff', 
                                           'hour', 'daily_volume_vol_diff', 'month', 'daily_vol_diff30', 'roc_diff', 'return_vol_16H', 'volume_vol_240M', 'min_vol_diff_pct', 'range_vol', 'oneD_returns_close', 
                                           'return_vol_30D', 'price_10DDiff', 'daily_volume_vol_diff30', 'day_of_week', 'volume_vol_16H', 'roc5'],
    "VDIFFC_1D": ['volume_vol_5D', 'price_10DDiff', 'volume_vol_10D', 'daily_vol_diff_pct30', 'range_vol', 'oneD_returns_close', 'day_of_month', 'volume_vol_30D', 'rsi', 'threeD_returns_close', 
                                           'range_vol_diff5', 'return_vol_10D', 'close_diff3', 'roc', 'daily_volume_vol_diff30', 'min_volume_vol_diff', 'return_vol_8H', 'return_vol_450M', 'daily_vol_diff', 'month',
                                             'close_diff', 'daily_volume_vol_diff_pct30', 'return_vol_30D', 'volume_vol_8H', 'volume_vol_16H', 'roc5', 'return_vol_240M', 'hour_vol_diff', 'cmf', 'min_vol_diff_pct', 'close_diff5'],
    "IDXP": ['return_vol_30D', 'threeD_stddev50', 'month', 'return_vol_450M', 'SPY_1D', 'oneD_returns_close',
             'min_volume_vol_diff_pct', 'price_10DDiff', 'oneD_stddev50', 'volume_vol_16H', 'min_volume_vol_diff', 
             'volume_vol_8H', 'daily_vol_diff_pct30', 'hour_vol_diff_pct', 'volume_vol_240M', 'SPY_diff', 'hour_volume_vol_diff',
               'volume_vol_30D', 'min_vol_diff_pct', 'return_vol_8H', 'hour', 'daily_vol_diff_pct', 'price_25DDiff', 'SPY_diff3', 
               'range_vol', 'rsi5', 'rsi', 'roc_diff', 'roc3', 'daily_volume_vol_diff', 'hour_vol_diff', 'return_vol_240M', 
               'close_diff', 'min_vol_diff'],
    "IDXP_1D": ['volume_vol_240M', 'roc', 'volume_vol_450M', 'roc_diff', 'SPY_diff', 'daily_volume_vol_diff30', 'rsi5', 'SPY_1D', 
            'range_vol_diff5', 'day_of_week', 'hour_volume_vol_diff_pct', 'daily_vol_diff_pct30', 'roc5', 'close_diff5', 
            'volume_vol_16H', 'v_diff_pct', 'volume_vol_30D', 'cmf', 'month', 'volume_vol_8H', 'threeD_returns_close', 
            'daily_vol_diff_pct', 'return_vol_8H', 'return_vol_240M', 'oneD_stddev50', 'day_of_month', 'range_vol', 
            'price_10DDiff', 'hour_vol_diff_pct', 'daily_vol_diff30', 'hour', 'return_vol_16H', 'return_vol_450M', 
            'daily_volume_vol_diff_pct', 'min_volume_vol_diff', 'hour_vol_diff', 'SPY_diff3'],
    "IDXC": ['rsi', 'daily_volume_vol_diff_pct', 'v_diff_pct', 'hour_volume_vol_diff', 'close_diff3', 'threeD_returns_close', 'return_vol_10D', 'min_volume_vol_diff', 
                                           'hour', 'daily_volume_vol_diff', 'month', 'daily_vol_diff30', 'roc_diff', 'return_vol_16H', 'volume_vol_240M', 'min_vol_diff_pct', 'range_vol', 'oneD_returns_close', 
                                           'return_vol_30D', 'price_10DDiff', 'daily_volume_vol_diff30', 'day_of_week', 'volume_vol_16H', 'roc5'],
    "IDXC_1D": ['volume_vol_5D', 'price_10DDiff', 'volume_vol_10D', 'daily_vol_diff_pct30', 'range_vol', 'oneD_returns_close', 'day_of_month', 'volume_vol_30D', 'rsi', 'threeD_returns_close', 
                                           'range_vol_diff5', 'return_vol_10D', 'close_diff3', 'roc', 'daily_volume_vol_diff30', 'min_volume_vol_diff', 'return_vol_8H', 'return_vol_450M', 'daily_vol_diff', 'month',
                                             'close_diff', 'daily_volume_vol_diff_pct30', 'return_vol_30D', 'volume_vol_8H', 'volume_vol_16H', 'roc5', 'return_vol_240M', 'hour_vol_diff', 'cmf', 'min_vol_diff_pct', 'close_diff5']
}

ENDPOINT_NAMES = {
"GAIN": "",
"GAIN_1D": "",
"GAINP": "",
"GAINP_1D": "",
"LOSERS": "",
"LOSERS_1D": "",
"LOSERSC": "",
"LOSERSC_1D": "",
"MA": "",
"MA_1D": "",
"MAP": "",
"MAP_1D": "",
"VDIFFC": "",
"VDIFFC_1D": "",
"VDIFFP": "",
"VDIFFP_1D": "",
"IDXC": "",
"IDXC_1D": "",
"IDXP": "",
"IDXP_1D": "",
}
