service: inv-alerts-pipeline
configValidationMode: warn
frameworkVersion: '3'


provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  timeout: 900
  deploymentBucket: 
    name: "yqalerts-serverless-bucket"
  environment:
    API_KEY: 'A_vXSwpuQ4hyNRj_8Rlw1WwVDWGgHbjp'

plugins:
  - serverless-step-functions
  - serverless-ignore

functions:
  analytics-production-line-cdvol:
    handler: analytics_production_line.cdvol_analytics_runner
    environment:
      ENV: "PROD_VAL"
      ALERTS_BUCKET: "inv-alerts"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-analytics-production-line-cdvol
  alerts-builder:
    handler: analytics_production_line.alerts_builder
    environment:
      PARTITION_ASSIGNMENT: "1"
      TRADING_DATA_BUCKET: "icarus-research-data"
      USER: "CM3"
      ALERTS_BUCKET: "inv-alerts"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-alerts-builder
  # training-data-builder:
  #   handler: historical_dataset_builder.build_historic_data
  #   environment:
  #     TRADING_DATA_BUCKET: "icarus-research-data"
  #     USER: "CM3"
  #   layers:
  #     - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
  #     - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
  #   role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
  #   name: inv-historical-dataset-builder-bfplus
  gain-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "GAIN,GAIN_1D,GAINP,GAINP_1D"
      ALERT_TYPE: "gainers"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: gain-xgboost-classifier
  losers-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "LOSERS,LOSERS_1D,LOSERSC,LOSERSC_1D"
      ALERT_TYPE: "losers"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: losers-xgboost-classifier
  ma-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "MA,MA_1D,MAP,MAP_1D"
      ALERT_TYPE: "most_actives"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: ma-xgboost-classifier
  cdvol-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "CDBFC,CDBFP,CDBFC_1D,CDBFP_1D"
      ALERT_TYPE: "cdvol"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: cdvol-xgboost-classifier

stepFunctions:
  stateMachines:
    invalerts-production-modeling:
      name: invalerts-production-modeling
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine runs the day_gainers process"
        StartAt: AnalyticsProcessor
        States:
          AnalyticsProcessor:
            Type: Parallel
            Branches:
              - StartAt: AnalyticsProductionLineCDVOL
                States:
                  AnalyticsProductionLineCDVOL:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:inv-analytics-production-line-cdvol:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            Next: Modeling
          Modeling:
            Type: Parallel
            Branches:
              - StartAt: cdvol-xgboost-classifier
                States:
                  cdvol-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:cdvol-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            End: true
