service: inv-alerts-pipeline
configValidationMode: warn
frameworkVersion: '3'


provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  timeout: 900
  deploymentBucket: 
    name: "yqalerts-serverless-bucket"
  environment:
    API_KEY: 'A_vXSwpuQ4hyNRj_8Rlw1WwVDWGgHbjp'

plugins:
  - serverless-step-functions
  - serverless-ignore

functions:
  analytics-production-line:
    handler: analytics_production_line.analytics_runner
    environment:
      TRADING_DATA_BUCKET: "icarus-research-data"
      USER: "CM3"
      ALERTS_BUCKET: "inv-alerts"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-analytics-production-line
  training-data-builder:
    handler: historical_dataset_builder.build_historic_data
    environment:
      TRADING_DATA_BUCKET: "icarus-research-data"
      USER: "CM3"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-historical-dataset-builder-bfplus
  gain-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "GAIN,GAIN_1D,GAINP,GAINP_1D"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: gain-xgboost-classifier
  losers-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "LOSERS,LOSERS_1D,LOSERSC,LOSERSC_1D"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: losers-xgboost-classifier
  vdiff-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "VDIFFC,VDIFFC_1D,VDIFFP,VDIFFP_1D"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: vdiff-xgboost-classifier
  ma-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "MA,MA_1D,MAP,MAP_1D"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: ma-xgboost-classifier
  idx-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "IDXC,IDXC_1D,IDXP,IDXP_1D"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: idx-xgboost-classifier

stepFunctions:
  stateMachines:
    # inv-alerts-pipeline:
    #   name: inv-alerts-pipeline
    #   role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
    #   alarms:
    #     topics:
    #       alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
    #     metrics:
    #       - executionsTimedOut
    #       - executionsFailed
    #       - executionsAborted
    #       - executionThrottled
    #     treatMissingData: missing
    #   definition:
    #     Comment: "This state machine constructs and executes trades based on results of the modeling engine"
    #     StartAt: analytics-production-line
    #     States:
    #       analytics-production-line:
    #         Type: Task
    #         Resource: arn:aws:lambda:us-east-1:456201388658:function:inv-analytics-production-line
    #         Retry:
    #         - ErrorEquals:
    #           - Lambda.ServiceException
    #           - Lambda.AWSLambdaException
    #           - Lambda.SdkClientException
    #           IntervalSeconds: 5
    #           MaxAttempts: 3
    #           BackoffRate: 2
    #         Next: End
    #       End:
    #           Type: Succeed
    invalerts-production-modeling:
      name: invalerts-production-modeling
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine runs the day_gainers process"
        StartAt: AnalyticsProcessor
        States:
          AnalyticsProcessor:
            Type: Task
            Resource:  "arn:aws:lambda:us-east-1:456201388658:function:inv-analytics-production-line:$LATEST"
            Retry:
              - ErrorEquals:
                - Lambda.ServiceException
                - Lambda.AWSLambdaException
                - Lambda.SdkClientException
                IntervalSeconds: 5
                MaxAttempts: 3
                BackoffRate: 2
            Next: Modeling
          Modeling:
            Type: Parallel
            Branches:
              - StartAt: losers-xgboost-classifier
                States:
                  losers-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:losers-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: gain-xgboost-classifier
                States:
                  gain-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:gain-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: idx-xgboost-classifier
                States:
                  idx-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:idx-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: ma-xgboost-classifier
                States:
                  ma-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:ma-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: vdiff-xgboost-classifier
                States:
                  vdiff-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:vdiff-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            End: true
