service: inv-alerts-pipeline
configValidationMode: warn
frameworkVersion: '3'


provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  stage: ${self:custom.stage}
  timeout: 900
  deploymentBucket: 
    name: "yqalerts-serverless-bucket"
  environment:
    API_KEY: 'A_vXSwpuQ4hyNRj_8Rlw1WwVDWGgHbjp'

plugins:
  - serverless-step-functions
  - serverless-ignore

custom:
  # defaultStage: ${self:custom.throwError('Stage is required. Please provide a stage using --stage.')}
  stage: ${opt:stage,'dev'}
  stages:
    - dev
    - prod
    # - prod
  dev:
    env: DEV
  prod:
    env: PROD
  # prod:
  #   env: PROD

functions:
  analytics-production-line-cdvol:
    handler: analytics_production_line.cdvol_analytics_runner
    environment:
      PARTITION_ASSIGNMENT: "cdvol"
      TRADING_DATA_BUCKET: "icarus-research-data"
      USER: "CM3"
      ALERTS_BUCKET: "inv-alerts"
      ENV: ${self:custom.${self:provider.stage}.env}
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-analytics-production-line-cdvol-${self:provider.stage}
  pcr-feature-builder:
    handler: pcr_features_production.run_process
    environment:
      ENV: ${self:custom.${self:provider.stage}.env}
      ALERTS_BUCKET: "inv-alerts"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-alerts-pcr-feature-builder-${self:provider.stage}
  analytics-production-line-trend:
    handler: analytics_production_line.trend_analytics_runner
    environment:
      PARTITION_ASSIGNMENT: "cdvol"
      TRADING_DATA_BUCKET: "icarus-research-data"
      USER: "CM3"
      ALERTS_BUCKET: "inv-alerts"
      ENV: ${self:custom.${self:provider.stage}.env}
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-analytics-production-line-trend-${self:provider.stage}
  cdvol-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "CDBFC_1D,CDBFP_1D"
      PORTFOLIO_STRATEGY: "CDVOLBF"
      ENV: ${self:custom.${self:provider.stage}.env}
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: cdvol-xgboost-classifier-${self:provider.stage}
  gain-xgboost-classifier-2H:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "CDGAINC_2H,CDGAINP_2H"
      PORTFOLIO_STRATEGY: "CDVOL_GAIN"
      ENV: ${self:custom.${self:provider.stage}.env}
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: cdvol-xgboost-classifier-gain-2H-${self:provider.stage}
  lose-xgboost-classifier-2H:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "CDLOSEC_2H,CDLOSEP_2H"
      PORTFOLIO_STRATEGY: "CDVOL_LOSE"
      ENV: ${self:custom.${self:provider.stage}.env}
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: cdvol-xgboost-classifier-lose-2H-${self:provider.stage}
  gain-xgboost-classifier-3D:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "CDGAINC_3D,CDGAINP_3D"
      PORTFOLIO_STRATEGY: "CDVOL_GAIN"
      ENV: ${self:custom.${self:provider.stage}.env}
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: cdvol-xgboost-classifier-gain-3D-${self:provider.stage}
  lose-xgboost-classifier-3D:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      STRATEGIES: "CDLOSEC_3D,CDLOSEP_3D"
      PORTFOLIO_STRATEGY: "CDVOL_LOSE"
      ENV: ${self:custom.${self:provider.stage}.env}
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: cdvol-xgboost-classifier-lose-3D-${self:provider.stage}
  data-validator:
    handler: data_validator.run_validation
    environment:
      ENV: ${self:custom.${self:provider.stage}.env}
      ALERTS_BUCKET: "inv-alerts"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:pytz:1
      - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python39:16
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-alerts-data-validator-${self:provider.stage}

stepFunctions:
  stateMachines:
    invalerts-production-modeling:
      name: invalerts-production-modeling-${self:provider.stage}
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine runs the day_gainers process"
        StartAt: AnalyticsProcessor
        States:
          AnalyticsProcessor:
            Type: Parallel
            Branches:
              - StartAt: AnalyticsProductionLineCDVOL
                States:
                  AnalyticsProductionLineCDVOL:
                    Type: Task
                    Resource:  
                      Fn::GetAtt: [analytics-production-line-cdvol, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: PCRFeatureBuilder
                States:
                  PCRFeatureBuilder:
                    Type: Task
                    Resource:  
                      Fn::GetAtt: [pcr-feature-builder, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            Next: Modeling
          Modeling:
            Type: Parallel
            Branches:
              - StartAt: cdvol-xgboost-classifier
                States:
                  cdvol-xgboost-classifier:
                    Type: Task
                    Resource: 
                      Fn::GetAtt: [cdvol-xgboost-classifier, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            Next: DataValidation
          DataValidation:
            Type: Task
            Resource: 
              Fn::GetAtt: [data-validator, Arn]
            Retry:
              - ErrorEquals:
                - Lambda.ServiceException
                - Lambda.AWSLambdaException
                - Lambda.SdkClientException
                IntervalSeconds: 5
                MaxAttempts: 3
                BackoffRate: 2
            Next: End
          End:
            Type: Succeed
    invalerts-production-modeling-trend:
      name: invalerts-production-modeling-trend-${self:provider.stage}
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine runs the day_gainers process"
        StartAt: AnalyticsProcessor
        States:
          AnalyticsProcessor:
            Type: Parallel
            Branches:
              - StartAt: AnalyticsProductionLineTREND
                States:
                  AnalyticsProductionLineTREND:
                    Type: Task
                    Resource:  
                      Fn::GetAtt: [analytics-production-line-trend, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            Next: Modeling
          Modeling:
            Type: Parallel
            Branches:
              - StartAt: gain-xgboost-classifier-2H
                States:
                  gain-xgboost-classifier-2H:
                    Type: Task
                    Resource: 
                      Fn::GetAtt: [gain-xgboost-classifier-2H, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: lose-xgboost-classifier-2H
                States:
                  lose-xgboost-classifier-2H:
                    Type: Task
                    Resource: 
                      Fn::GetAtt: [lose-xgboost-classifier-2H, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: gain-xgboost-classifier-3D
                States:
                  gain-xgboost-classifier-3D:
                    Type: Task
                    Resource: 
                      Fn::GetAtt: [gain-xgboost-classifier-3D, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: lose-xgboost-classifier-3D
                States:
                  lose-xgboost-classifier-3D:
                    Type: Task
                    Resource: 
                      Fn::GetAtt: [lose-xgboost-classifier-3D, Arn]
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            Next: End
          End:
            Type: Succeed