service: inv-alerts-pipeline
configValidationMode: warn
frameworkVersion: '3'


provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  timeout: 900
  deploymentBucket: 
    name: "yqalerts-serverless-bucket"
  environment:
    API_KEY: 'A_vXSwpuQ4hyNRj_8Rlw1WwVDWGgHbjp'

plugins:
  - serverless-step-functions
  - serverless-ignore

functions:
  analytics-production-line:
    handler: analytics_production_line.analytics_runner
    environment:
      TRADING_DATA_BUCKET: "icarus-research-data"
      USER: "CM3"
      ALERTS_BUCKET: "inv-alerts"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-analytics-production-line
  historical-dataset-builder:
    handler: historical_dataset_builder.build_historic_data
    environment:
      TRADING_DATA_BUCKET: "icarus-research-data"
      USER: "CM3"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: inv-historical-dataset-builder
  bfc-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      TITLE: "bfC"
      ENDPOINT_NAMES: "invalerts-xgb-bfc-classifier, invalerts-xgb-bfc-1d-classifier"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: bfc-xgboost-classifier
  bfp-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      TITLE: "bfP"
      ENDPOINT_NAMES: "invalerts-xgb-bfp-classifier, invalerts-xgb-bfp-1d-classifier"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: bfp-xgboost-classifier
  indexc-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      TITLE: "indexC"
      ENDPOINT_NAMES: "invalerts-xgb-indexc-classifier"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: indexc-xgboost-classifier
  indexp-xgboost-classifier:
    handler: xgboost_classifier.invoke_model
    environment:
      PREDICTIONS_BUCKET: "inv-alerts-trading-data"
      ALERTS_BUCKET: "inv-alerts"
      TITLE: "indexP"
      ENDPOINT_NAMES: "invalerts-xgb-indexp-classifier"
    layers:
      - arn:aws:lambda:us-east-1:456201388658:layer:scout_lambdas_ta:5
    role: arn:aws:iam::456201388658:role/batch-scout-lambdaRole
    name: indexp-xgboost-classifier

stepFunctions:
  stateMachines:
    inv-alerts-pipeline:
      name: inv-alerts-pipeline
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine constructs and executes trades based on results of the modeling engine"
        StartAt: analytics-production-line
        States:
          analytics-production-line:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:456201388658:function:inv-analytics-production-line
            Retry:
            - ErrorEquals:
              - Lambda.ServiceException
              - Lambda.AWSLambdaException
              - Lambda.SdkClientException
              IntervalSeconds: 5
              MaxAttempts: 3
              BackoffRate: 2
            Next: End
          End:
              Type: Succeed
    invalerts-production-modeling:
      name: invalerts-production-modeling
      role: arn:aws:iam::456201388658:role/service-role/StepFunctions-Gainers-Production-Modeling-role-72889a0b
      alarms:
        topics:
          alarm: arn:aws:sns:us-east-1:456201388658:yqalerts-production-modeling
        metrics:
          - executionsTimedOut
          - executionsFailed
          - executionsAborted
          - executionThrottled
        treatMissingData: missing
      definition:
        Comment: "This state machine runs the day_gainers process"
        StartAt: AnalyticsProcessor
        States:
          AnalyticsProcessor:
            Type: Task
            Resource:  "arn:aws:lambda:us-east-1:456201388658:function:inv-analytics-production-line:$LATEST"
            Retry:
              - ErrorEquals:
                - Lambda.ServiceException
                - Lambda.AWSLambdaException
                - Lambda.SdkClientException
                IntervalSeconds: 5
                MaxAttempts: 3
                BackoffRate: 2
            Next: Modeling
          Modeling:
            Type: Parallel
            Branches:
              - StartAt: bfc-xgboost-classifier
                States:
                  bfc-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:bfc-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: bfp-xgboost-classifier
                States:
                  bfp-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:bfp-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: indexc-xgboost-classifier
                States:
                  indexc-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:indexc-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
              - StartAt: indexp-xgboost-classifier
                States:
                  indexp-xgboost-classifier:
                    Type: Task
                    Resource:  "arn:aws:lambda:us-east-1:456201388658:function:indexp-xgboost-classifier:$LATEST"
                    Retry:
                      - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        IntervalSeconds: 5
                        MaxAttempts: 3
                        BackoffRate: 2
                    End: true
            End: true
